### ISSUE TITLE
can not install in vscode

### ISSUE THREAD

**Issue by sunshe35** [laike9m/Cyberbrain#107]
**Describe the bug**

**Code to reproduce the bug**
Please provide a code snippet that can reproduce the bug
```python
[paste your code here]
```

**Screenshots and/or error messages**

If you see any error message, please also paste it here.

**Environment:**
Please provide the following information:
- OS you're using
- Python version
- Cyberbrain Python lib version
- Cyberbrain VS Code extension version

the error:
![image](https://user-images.githubusercontent.com/16757906/115149292-f96a5a00-a095-11eb-8a86-b54ec61cb744.png)

I can not install  it in vscode too.

**Comment by laike9m** [comment]
Doesn't seem like a bug with Cyberbrain itself. Maybe related to:
https://stackoverflow.com/questions/38466944/can-not-open-zip-file-after-downloading-through-nodejs-application-because-of-in

I would suggest installing the extension from the UI. Does that work?

**Comment by sunshe35** [comment]
I can install it from the UI in my work PC.
I assume this is a problem with the Node environment configuration on my home computer
