### ISSUE TITLE
Can not install on Python3

### ISSUE THREAD

**Issue by nanfang2000** [laike9m/Cyberbrain#111]
C:\WINDOWS\system32>pip3 install cyberbrain
ERROR: Could not find a version that satisfies the requirement cyberbrain
ERROR: No matching distribution found for cyberbrain

**Comment by laike9m** [comment]
Please follow the [template](https://github.com/laike9m/Cyberbrain/issues/new?assignees=&labels=bug&template=bug_report.md&title=) to provide necessary information.

**Comment by nanfang2000** [comment]
**Describe the bug**
Can not install on Python3.6..7

**Code to reproduce the bug**
```python
pip3 install cyberbrain
```

**Screenshots and/or error messages**
ERROR: Could not find a version that satisfies the requirement cyberbrain
ERROR: No matching distribution found for cyberbrain

**Environment:**
Please provide the following information:
- OS you're using: Windows 10
- Python version: 3.6.7
- Cyberbrain Python lib version: Not installed yet
- Cyberbrain VS Code extension version: Not installed yet

**Comment by laike9m** [comment]
Cyberbrain only supports Python >= 3.7.0
