### ISSUE TITLE
Can't connect to RPC server

### ISSUE THREAD

**Issue by jesusdpa1** [laike9m/Cyberbrain#119]
**Describe the bug**
Can't connect to RPC server message when running cyberbrain in Pycharm. Is there a way to run cyberbrain in either pycharm or jupyterlab/notebook? 

**Code to reproduce the bug**
Please provide a code snippet that can reproduce the bug
```python
from cyberbrain import trace

# As of now, you can only have one @trace decorator in the whole program.
# We may change this in version 2.0, see https://github.com/laike9m/Cyberbrain/discussions/73

@trace  # Disable tracing with `@trace(disabled=True)`
def foo():
    print('hi')
    
foo()
```

**Screenshots and/or error messages**

If you see any error message, please also paste it here.

**Environment:**
Please provide the following information:
- OS you're using: Linux
- Python version: 3.7
- Cyberbrain Python lib version: latest
- Cyberbrain VS Code extension version: None

**Comment by laike9m** [comment]
Hi Jesus, you can run your program from PyCharm (or anywhere else), that'll work. But the visulization part relies on VS Code. Check out this issue: https://github.com/laike9m/Cyberbrain/issues/24

**Comment by jesusdpa1** [comment]
Thanks!
