### ISSUE TITLE
can not install cyberbrain library

### ISSUE THREAD

**Issue by wloverine** [laike9m/Cyberbrain#135]
**Describe the bug**
I tried to install cyberbrain by the following command:
```shell
ERROR: Could not find a version that satisfies the requirement cyberbrain (from versions: none)
ERROR: No matching distribution found for cyberbrain
```

**Environment:**
Please provide the following information:
- windows 1909
- anaconda python 3.6.13

**Comment by laike9m** [comment]
Cyberbrain supports Python 3.7+. 3.6 is not supported unfortunately.
