### ISSUE TITLE
Does it not support recursive functions?

### ISSUE THREAD

**Issue by xirikm** [laike9m/Cyberbrain#43]
When I run the following code to calculate the Fibonacci sequence recursively, I got an `AssertionError`:

```python
from cyberbrain import trace

@trace
def fibo(n):
    if n <= 1:
        return n
    else:
        return fibo(n - 1) + fibo(n - 2)

print(fibo(3))
```

I have also tested some other recursive functions, and they all have this problem.  This may be a bug that needs to be fixed

**Comment by laike9m** [comment]
Thanks for the bug report, it should be easy to fix.

**Comment by laike9m** [comment]
Try the latest version 0.0.7, and it should be fixed.
