### ISSUE TITLE
Confusing graph when there are multiple variables in one line

### ISSUE THREAD

**Issue by no1xsyzy** [laike9m/Cyberbrain#47]
Example code:
```python
from cyberbrain import trace


@trace
def fib(n):
    a, b = 0, 1
    for _ in range(n):
        a, b = b, a+b
    return b


if __name__ == '__main__':
    fib(3)
```

Result:
![image](https://user-images.githubusercontent.com/7346170/95645031-a82d4c80-0aed-11eb-92bb-44bc27155dbe.png)

Maybe different name within one line can be separated? Alike this workaround: 
```python
from cyberbrain import trace


@trace
def fib(n):
    (a,
     b) = 0, 1
    for _ in range(n):
        (a,
         b) = b, a+b
    return b


if __name__ == '__main__':
    fib(3)
```

Result:
![image](https://user-images.githubusercontent.com/7346170/95645054-f93d4080-0aed-11eb-8e12-b7c285e6681f.png)

**Comment by laike9m** [comment]
Thanks for the feedback, edge cases like this is just what I need 😂

I'll take a look.

**Comment by laike9m** [comment]
Just some rough ideas and we can dicuss.

I think Cyberbrain should respect the original code, and show the trace graph that matches the code no matter what. It is true that by putting nodes at different lines would make it look better, but at the same time, it can confuse people, not to mention there are countless cases to handle.

I'm leaning towards closing this issue, unless you have a very compelling reason, plus a side-effect free way to support it.

**Comment by no1xsyzy** [comment]
Sorry I didn't made it clear.
Rather than really mark them as different lines, the line numbers are kept untouched, only put variables on different lines.
Some photo editing:
![图片](https://user-images.githubusercontent.com/7346170/95655232-6675c380-0b38-11eb-8b6e-8dab0e7b4ccd.png)

**Comment by laike9m** [comment]
Got it. I think this is a good idea, but it's not easy to implement. I'll keep it open until I have an idea.

**Comment by laike9m** [comment]
Try again, the graph is correct now.
