### ISSUE TITLE
"Can't connect to RPC server" for VS Code 1.53.0

### ISSUE THREAD

**Issue by Jakkwj** [laike9m/Cyberbrain#85]
- I used VS Code 1.53.0, and run without debugging and nothing happened and the terminal keeps telling me ``Can't connect to RPC server``
- so,,,what happened?

Thanks a lot~

**Comment by laike9m** [comment]
Hi, thanks for the bug report. Could you provide the following information?
- OS you're using
- Python version
- Cyberbrain Python lib version and VS Code extension version.

Thanks

**Comment by Jakkwj** [comment]
- OS: Ubuntu20.04
- Python 3.8.5
- Cyberbrain 0.1.1
- VS Code extension 0.1.1
I will try another computer(my laptop) later, thanks~

> Hi, thanks for the bug report. Could you provide the following information?
> 
> * OS you're using
> * Python version
> * Cyberbrain Python lib version and VS Code extension version.
> 
> Thanks

**Comment by Jakkwj** [comment]
under my laptop is fine:
- OS: Ubuntu16.04
- Python 3.7.8
- VS Code 1.52.1
- Cyberbrain 0.1.1
- VS Code extension 0.1.1

**Comment by laike9m** [comment]
I can confirm the bug. It is brought in due to the latest version of VS Code using a newer version of nodejs (12.18.3 vs 12.14.1).

The root cause it described in https://github.com/gitpod-io/gitpod/issues/2435.

Will fix it ASAP.

**Comment by laike9m** [comment]
Try update the VS Code extension to 0.1.2, it should work now. If not, please let me know.

**Comment by zhuima** [comment]
update VS Code extension: v0.1.3 it's work fine

**Comment by e-lo** [comment]
I'm getting same error with below VS Code for v0.1.4 of the VS Code extension:

```
Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:45:54.515Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0
```

**Comment by laike9m** [comment]
@e-lo could you paste the code snippet you're using, and let me know what operations you did?

**Comment by e-lo** [comment]
Here a simplified version that triggers the error below when running from vscode w/out debugging:

```python
import pytest

from cyberbrain import trace

def my_function(x):
    y = x + 2

    x += 5

    z = y*x

    return z

@trace
def test_read_metcouncil_net_with_params(request):
    if request: print("\n--Starting:", request.node.name)
    x = 0
    x += 1
    my_z = my_function(x)
    return my_z

if __name__ == '__main__':
    test_read_metcouncil_net_with_params(None)
```

Error:
```
 /usr/bin/env /Users/elizabeth/anaconda3/envs/wrangler/bin/python /Users/elizabeth/.vscode/extensions/ms-python.python-2021.2.582707922/pythonFiles/lib/python/debugpy/launcher 49536 -- /Users/elizabeth/Documents/urbanlabs/MetCouncil/working/Lasso/tests/test_temp.py 
Can't connect to RPC server
```

The conda environment `wrangler` has cyberbrain installed from pip.

**Comment by laike9m** [comment]
Just to make sure, you do have the Cyberbrain vscode extension installed
right?

If so, can you run `lsof -i:1989` and paste the output?

**Comment by e-lo** [comment]
> You do have the Cyberbrain vscode extension installed right?

Yes, v 0.1.4

> run `lsof -i:1989`

```
COMMAND     PID      USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
Code\x20H 54760 elizabeth   30u  IPv6 0x878a6488c40a6ba3      0t0  TCP *:tr-rsrb-p3 (LISTEN)
```

**Comment by laike9m** [comment]
I honestly don't know the root cause as the setup sounds correct. Could you
try opening the developer tool and webview developer tool and see if
there's any error messages there?

[image: image.png]
