### ISSUE TITLE
does not work if 'cv2.xxxx' performs on big image

### ISSUE THREAD

**Issue by notorious-eric** [laike9m/Cyberbrain#86]
Hi, I found that once 'cv2.xxxx' is mentioned in the function, cyberbrain stops working. If I create a numpy array it is okay.

**Comment by laike9m** [comment]
Thanks for the bug report. Do you mind post a snippet that can reproduce this bug?

**Comment by notorious-eric** [comment]
just a simple cv2.imread can work, however when put into a loop it is not working.

```
import cv2
import os
import numpy as np
from cyberbrain import trace
@trace
def main():
    image_path =None
    image_dir = 'ppt_example/test3/'
    colors = [np.array([0, 0, 255]), np.array([0, 255, 0]), np.array([255, 0, 0])]
    if image_path:
        image_paths = [image_path]
    else:
        image_paths = [os.path.join(image_dir, image_name) for image_name in os.listdir(image_dir)]


    for image_path in image_paths:
        image_name = os.path.split(image_path)[1]
        image = cv2.imread(image_path)

    return image
```

**Comment by laike9m** [comment]
Got it, will take a look.

**Comment by laike9m** [comment]
What error did you see? I run your script and it works fine.

![image](https://user-images.githubusercontent.com/2592205/107480124-f6e90280-6b30-11eb-958c-dd34e51d8929.png)

**Comment by laike9m** [comment]
Also, could you provide the following information?

- OS you're using
- Python version
- Cyberbrain Python lib version and VS Code extension version.

**Comment by notorious-eric** [comment]
The error is that I can not see the graph or any result, there are no new windows if cv2.imread appear in a loop.
OS: windows 10
python version:3.7.6
cyberbrain python lib version:0.1.1
VSCode extension version:0.1.2
opencv-python  version:4.5.1.48

**Comment by laike9m** [comment]
I was testing on Python 3.8, so maybe that's the difference. I'll run on 3.7 tomorrow and get back to you.

**Comment by notorious-eric** [comment]
I try cv2.imread on pictures of a smaller size and it is okay now, the previous size of the picture is about 3600*2800, now for smaller size such as 1024*1024 it is okay.

**Comment by laike9m** [comment]
Thanks for providing this information

**Comment by laike9m** [comment]
Yep I can reproduce the bug with big images. Fixing it now.

**Comment by laike9m** [comment]
Upgrade the extension to 0.1.3 and it should work.

**Comment by notorious-eric** [comment]
Thank you very much!

**Comment by laike9m** [comment]
No problem
