### ISSUE TITLE
It will create a blank file

### ISSUE THREAD

**Issue by KikyoLover** [laike9m/Cyberbrain#89]
**Describe the bug**
As the title says, it will create a blank file named 'tmp/cyberbrain.txt' in my root directory. How to change the path or make it not
 show again?

![Snipaste_2021-02-16_17-08-11](https://user-images.githubusercontent.com/34465538/108041496-93ebf400-7079-11eb-9305-f87f282c0c1b.png)

**Environment:**
Please provide the following information:
- OS  Windows 10 19042.804
- Python version  3.8.5
- Cyberbrain Python lib version 0.1.1
- Cyberbrain VS Code extension version 0.1.3

**Comment by laike9m** [comment]
That's the log file, and the behavior is expected:
https://github.com/laike9m/Cyberbrain/blob/master/cyberbrain-vsc/src/utils.ts

I should pick a different place for Windows though.

**Comment by laike9m** [comment]
Fixed
