### ISSUE TITLE
ImportError: No module named cyberbrain

### ISSUE THREAD

**Issue by zealot-shin** [laike9m/Cyberbrain#90]
after installed cyberbrain in vscode, i wrote following line in my python file

from cyberbrain import trace

but when i tried running without debugging, following error occurred:
ImportError: No module named cyberbrain

It seems that cyberbrain is not enabled in my workspace.but from vscode extensions  view I can see this extension is enabled.

I tried installing cyberbrain by pip install, but couldnot find the repo:
ERROR: Could not find a version that satisfies the requirement cyberbrain (from versions: none)
ERROR: No matching distribution found for cyberbrain

How can I make cyberbrain work in my case?

**Comment by laike9m** [comment]
Please follow the template and provide necessary information so I can help you.

https://github.com/laike9m/Cyberbrain/issues/new?assignees=&labels=bug&template=bug_report.md&title=

**Comment by laike9m** [comment]
dup of #91, closed
